stages:
  train:
    cmd: python scripts/train.py
    deps:
    - data/raw/dataset.csv
    - scripts/train.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
    plots:
    - metrics/metrics.tsv
